import { NextRequest, NextResponse } from 'next/server';
import { Octokit } from '@octokit/rest';

export async function POST(req: NextRequest) {
  try {
    const { code, language, problemTitle, topic } = await req.json();

    if (!code || !language || !problemTitle) {
      return NextResponse.json({ error: 'code, language, problemTitle are required' }, { status: 400 });
    }

    const token    = process.env.GITHUB_TOKEN;
    const username = process.env.GITHUB_USERNAME;
    const repoName = 'DSA-Problems';

    // ── Demo fallback ────────────────────────────────────
    if (!token || !username) {
      return NextResponse.json({
        success: true,
        demo: true,
        message: `[Demo] Would push to ${username ?? 'your-username'}/${repoName}/${topic ?? 'General'}/${problemTitle}.${langExt(language)}`,
        url: `https://github.com/${username ?? 'your-username'}/${repoName}`,
      });
    }

    const octokit = new Octokit({ auth: token });

    // 1. Ensure the repo exists (create if not)
    let repoExists = false;
    try {
      await octokit.repos.get({ owner: username, repo: repoName });
      repoExists = true;
    } catch {
      repoExists = false;
    }

    if (!repoExists) {
      await octokit.repos.createForAuthenticatedUser({
        name:        repoName,
        description: 'Auto-generated by PlacementHub 🚀 — DSA solutions organized by topic',
        private:     false,
        auto_init:   true,
      });
      // Give GitHub a moment to init
      await new Promise(r => setTimeout(r, 1500));
    }

    // 2. Build file path
    const safeTitle = problemTitle.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
    const safeTopic = (topic ?? 'general').toLowerCase().replace(/\s+/g, '-');
    const ext       = langExt(language);
    const filePath  = `${safeTopic}/${safeTitle}.${ext}`;

    // 3. Check if file already exists (need its SHA to update)
    let fileSha: string | undefined;
    try {
      const { data } = await octokit.repos.getContent({ owner: username, repo: repoName, path: filePath });
      if (!Array.isArray(data)) fileSha = data.sha;
    } catch { /* file doesn't exist yet, that's fine */ }

    // 4. Commit the file
    const content = Buffer.from(addHeader(code, problemTitle, language)).toString('base64');
    const commitMsg = `✅ Add ${problemTitle} [${language}] — PlacementHub auto-push`;

    const { data: fileData } = await octokit.repos.createOrUpdateFileContents({
      owner:   username,
      repo:    repoName,
      path:    filePath,
      message: commitMsg,
      content,
      sha:     fileSha,
    });

    return NextResponse.json({
      success: true,
      demo:    false,
      url:     fileData.content?.html_url ?? `https://github.com/${username}/${repoName}`,
      commit:  fileData.commit.sha?.slice(0, 7),
      path:    filePath,
      message: `✅ Pushed to ${username}/${repoName}/${filePath}`,
    });

  } catch (err: any) {
    console.error('[github/push] error:', err);
    return NextResponse.json({ error: err.message || 'GitHub push failed' }, { status: 500 });
  }
}

function langExt(lang: string): string {
  const map: Record<string, string> = {
    cpp: 'cpp', c: 'c', java: 'java', python: 'py',
    py: 'py', js: 'js', javascript: 'js', sql: 'sql',
  };
  return map[lang.toLowerCase()] ?? 'txt';
}

function addHeader(code: string, title: string, lang: string): string {
  const date = new Date().toISOString().split('T')[0];
  const comments: Record<string, [string, string]> = {
    cpp:    ['// ', ''],
    c:      ['// ', ''],
    java:   ['// ', ''],
    python: ['# ',  ''],
    py:     ['# ',  ''],
    js:     ['// ', ''],
    sql:    ['-- ', ''],
  };
  const [lc] = comments[lang.toLowerCase()] ?? ['// ', ''];
  return `${lc}Problem: ${title}\n${lc}Language: ${lang}\n${lc}Date: ${date}\n${lc}Auto-pushed by PlacementHub 🚀\n\n${code}`;
}
